title: Viktor Edvardsson
email: viktoredvardsson@gmail.com
description: Viktor Edvardsson är konceptutvecklare och grafisk formgivare.
baseurl: '/ve.com'
url: 'https://www.viktoredvardsson.com'
twitter_username: viktoredv
github_username: ''
plugins:
  - jekyll-feed
